### ISSUE TITLE
CTRL+C stops all program if using RPIO.PWM

### ISSUE THREAD

**Issue by tuomas2** [metachris/RPIO#19]
Pressing CTRL+C quits the program if it is using RPIO.PWM, even though I have set try-except KeyboardException handler and have many other threads running as well.

**Comment by mkj** [comment]
I think setup_sighandlers should only handle signals 1-32. 33 onwards are realtime signals. The following whitelist are safe to ignore, they don't terminate the process or are handled by Python

SIGCHLD
SIGCONT
SIGTSTP
SIGTTIN
SIGTTOU
SIGURG
SIGWINCH
SIGPIPE (by Python)
SIGINT (by Python)
SIGIO
