### ISSUE TITLE
not really an issue...Great Work!

### ISSUE THREAD

**Issue by dmedine** [metachris/RPIO#66]
Hi. I am developing a pi based analog to digital device for the neuroscience lab where I work (Swartz Center for Computational Neuroscience). In addition to having multiple analog inputs (I use the TI ads1015 and go through I2C) it is to generate a TTL pulse for triggering purposes. I found this library and just dropped pwm.c and pwm.h into my project folder, commented out the main function and compiled it as a library so that my application (C based) can generate the desired signal. This took all of 5 minutes and it works beautifully with all the modularity I need. Thank you so much for such an excellent utility and a project that is so well set up! This is how all code should be.
-David Medine

**Comment by metachris** [comment]
Hello!

Thank you for the kind words, it literally made my day! :) 
I'm glad its useful to you and was easy to work with!

Best regards,
Chris
