### ISSUE TITLE
KivyPie only showing a Terminal!

### ISSUE THREAD

**Issue by RedChallenger4** [metachris/RPIO#83]
The first thing that popped up was a terminal asking for login and password.

So I entered the login and password. Yet, after it displayed "Welcome to KivyPie", it only showed a terminal below it (i.e. shows ' sysop@kivypie' and that's it)

How do I access the part about game/app development?

**Comment by RedChallenger4** [comment]
By the way, I installed by reading the KivyPie image into SD card.

**Comment by wgwz** [comment]
Wait, why is this in RPIO?

**Comment by RedChallenger4** [comment]
I thought this was the Group page for problems with installing/using KivyPie?

**Comment by wgwz** [comment]
No, this is the wrong place (I think). RPIO is a Python library for dealing with the GPIO pins on a Raspberry Pi. Nothing to do with Kivy (out of the box).

**Comment by RedChallenger4** [comment]
I think the website wasn't updated because the help link lead me here. Is there an updated link other than StackExchange (tried that)?

**Comment by K1773R** [comment]
no. this is the RPIO repository with a python module for GPIO handling.

**Comment by wgwz** [comment]
@RedChallenger4 You should close the issue here. This is definitely not the right place.
